l seek 1
h seek -1
. seek +0.01
, seek -0.03
m seek +0.01
n seek -0.01
L seek 5
H seek -5
> seek +0.05
< seek -0.05
j script-binding uosc/next #menu: Analysis > next clip
k script-binding uosc/prev #menu: Analysis > previous clip
g script-binding uosc/first #menu: Analysis > first clip
G script-binding uosc/last #menu: Analysis > last clip
x script-binding tag-file-quick #menu: Analysis > quick surfer tag
;-r script-binding tag-file #menu: Analysis > add full tags
;-d script-binding tag-file-delete #menu: Analysis > mark for deletion
;-u script-binding untag-file #menu: Analysis > undo tags
;-c script-binding clone-tagged-file #menu: Analysis > clone file
;-a script-binding uosc/menu #menu: Analysis > open analysis menu
E script-binding trigger_nvim #menu: Analysis > nvim
f script-binding trigger_flameshot #menu: Analysis > screenshot via flameshot
s screenshot video #menu: Analysis > screenshot
#rename-file
#<keybind> seek 0 absolute-percent ; show-text "Seek to the beginning" ; set pause no
: script-binding command-mode #menu: Analysis > command mode
z script-binding Blackbox
#N script-binding navigator
