hr-seek=yes
keep-open=always
#keep-open-pause=yes
loop-playlist=no
loop-file=no
sub-auto=all
screenshot-template='%x%F.zX%ws-%wT'
sub-fonts-dir=~/.config/profiles/mpx/scripts/fonts
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
osc=no # required so both UIs don't conflict
osd-bar=no # uosc osc
border=no # uosc osc
#profile=low-latency # decrease latency
#opengl-glfinish=yes # Latency. Can reduce buffering in the graphics driver
#opengl-swapinterval=0 # Latency. can reduce buffer in graphics driver
